server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yiqing?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jhonny
    password: baibing123